openapi: 3.0.2
info:
  version: 1.0.0
  title: Game Server
  license:
    name: None
    url: https://choosealicense.com/no-permission/
  description: |
    OpenAPI specification of game server API
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: Bearer <token>
security:
  - BearerAuth: []
tags:
  - name: User
    description: Operations about user
  - name: Auth
    description: Operations about Authentication
  - name: Game
    description: Game related things
servers:
  - url: 'https://localhost:3000'
    description: Localhost server
paths:
  /api/user:
    $ref: paths/api/user.yaml
  /api/user/game_events:
    $ref: paths/api/user/game_events.yaml
  /api/sessions:
    $ref: paths/api/sessions.yaml