openapi: 3.0.2
info:
  version: 1.0.0
  title: Game Server
  license:
    name: None
    url: https://choosealicense.com/no-permission/
  description: |
    OpenAPI specification of game server API
components:
  securitySchemes:
    accessToken:
      type: apiKey
      in: header
      name: Access-Token
      description: Access-Token
    client:
      type: apiKey
      in: header
      name: Client
      description: Client
    tokenType:
      type: apiKey
      in: header
      name: Token-Type
      description: Token type must be set to `Bearer` always
    uid:
      type: apiKey
      in: header
      name: uid
      description: User email
security:
  - accessToken: []
    client: []
    tokenType: []
    uid: []
tags:
  - name: User
    description: Operations about user
  - name: Auth
    description: Operations about Authentication
  - name: Game
    description: Game related things
servers:
  - url: 'https://localhost:3000'
    description: Localhost server
paths:
  /api/user:
    $ref: paths/api/user.yaml
  /api/user/game_events:
    $ref: paths/api/user/game_events.yaml
  /api/sessions:
    $ref: paths/api/sessions.yaml